// Autogenerated from PyBinding.addin.xml

using System.Reflection;

[assembly: AssemblyProduct ("MonoDevelop")]
[assembly: AssemblyTitle ("Protobuild Support")]
[assembly: AssemblyDescription ("Protobuild Support")]
[assembly: AssemblyVersion ("1.0")]
[assembly: AssemblyCopyright ("MIT X11")]
