
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.Protobuild
{
	internal partial class GtkProtobuildModuleConfigurationWidget
	{
		private global::Gtk.HBox mainHBox;
		
		private global::Gtk.EventBox leftBorderEventBox;
		
		private global::Gtk.EventBox projectConfigurationTableEventBox;
		
		private global::Gtk.VBox projectConfigurationVBox;
		
		private global::Gtk.EventBox projectConfigurationTopEventBox;
		
		private global::Gtk.Table projectConfigurationTable;
		
		private global::Gtk.Button browseButton;
		
		private global::Gtk.CheckButton createGitIgnoreFileCheckBox;
		
		private global::Gtk.Label locationLabel;
		
		private global::Gtk.DrawingArea locationSeparator;
		
		private global::Gtk.Entry locationTextBox;
		
		private global::Gtk.Label moduleNameLabel;
		
		private global::Gtk.Entry moduleNameTextBox;
		
		private global::Gtk.DrawingArea solutionNameSeparator;
		
		private global::Gtk.CheckButton useGitCheckBox;
		
		private global::Gtk.HBox versionControlLabelHBox;
		
		private global::Gtk.Label versionControlSpacerLabel;
		
		private global::Gtk.Label versionControlLabel;
		
		private global::Gtk.EventBox projectConfigurationBottomEventBox;
		
		private global::Gtk.EventBox projectConfigurationRightBorderEventBox;
		
		private global::Gtk.EventBox eventBox;
		
		private global::Gtk.VBox previewProjectFolderVBox;
		
		private global::MonoDevelop.Ide.Projects.GtkProjectFolderPreviewWidget projectFolderPreviewWidget;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.Protobuild.GtkProtobuildModuleConfigurationWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.Protobuild.GtkProtobuildModuleConfigurationWidget";
			// Container child MonoDevelop.Protobuild.GtkProtobuildModuleConfigurationWidget.Gtk.Container+ContainerChild
			this.mainHBox = new global::Gtk.HBox ();
			this.mainHBox.Name = "mainHBox";
			// Container child mainHBox.Gtk.Box+BoxChild
			this.leftBorderEventBox = new global::Gtk.EventBox ();
			this.leftBorderEventBox.WidthRequest = 30;
			this.leftBorderEventBox.Name = "leftBorderEventBox";
			this.mainHBox.Add (this.leftBorderEventBox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.mainHBox [this.leftBorderEventBox]));
			w1.Position = 0;
			w1.Expand = false;
			// Container child mainHBox.Gtk.Box+BoxChild
			this.projectConfigurationTableEventBox = new global::Gtk.EventBox ();
			this.projectConfigurationTableEventBox.WidthRequest = 561;
			this.projectConfigurationTableEventBox.Name = "projectConfigurationTableEventBox";
			// Container child projectConfigurationTableEventBox.Gtk.Container+ContainerChild
			this.projectConfigurationVBox = new global::Gtk.VBox ();
			this.projectConfigurationVBox.Name = "projectConfigurationVBox";
			// Container child projectConfigurationVBox.Gtk.Box+BoxChild
			this.projectConfigurationTopEventBox = new global::Gtk.EventBox ();
			this.projectConfigurationTopEventBox.Name = "projectConfigurationTopEventBox";
			this.projectConfigurationVBox.Add (this.projectConfigurationTopEventBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.projectConfigurationVBox [this.projectConfigurationTopEventBox]));
			w2.Position = 0;
			// Container child projectConfigurationVBox.Gtk.Box+BoxChild
			this.projectConfigurationTable = new global::Gtk.Table (((uint)(6)), ((uint)(3)), false);
			this.projectConfigurationTable.Name = "projectConfigurationTable";
			this.projectConfigurationTable.RowSpacing = ((uint)(7));
			this.projectConfigurationTable.ColumnSpacing = ((uint)(6));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.browseButton = new global::Gtk.Button ();
			this.browseButton.CanFocus = true;
			this.browseButton.Name = "browseButton";
			this.browseButton.UseUnderline = true;
			this.browseButton.BorderWidth = ((uint)(1));
			this.browseButton.Label = "Browse...";
			this.projectConfigurationTable.Add (this.browseButton);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.browseButton]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(2));
			w3.RightAttach = ((uint)(3));
			w3.XPadding = ((uint)(5));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.createGitIgnoreFileCheckBox = new global::Gtk.CheckButton ();
			this.createGitIgnoreFileCheckBox.CanFocus = true;
			this.createGitIgnoreFileCheckBox.Name = "createGitIgnoreFileCheckBox";
			this.createGitIgnoreFileCheckBox.Label = "Create a .gitignore file to ignore inessential files.";
			this.createGitIgnoreFileCheckBox.Active = true;
			this.createGitIgnoreFileCheckBox.DrawIndicator = true;
			this.createGitIgnoreFileCheckBox.UseUnderline = true;
			this.projectConfigurationTable.Add (this.createGitIgnoreFileCheckBox);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.createGitIgnoreFileCheckBox]));
			w4.TopAttach = ((uint)(5));
			w4.BottomAttach = ((uint)(6));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.locationLabel = new global::Gtk.Label ();
			this.locationLabel.Name = "locationLabel";
			this.locationLabel.Xpad = 5;
			this.locationLabel.Xalign = 1F;
			this.locationLabel.LabelProp = "Location:";
			this.locationLabel.Justify = ((global::Gtk.Justification)(1));
			this.projectConfigurationTable.Add (this.locationLabel);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.locationLabel]));
			w5.TopAttach = ((uint)(2));
			w5.BottomAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.locationSeparator = new global::Gtk.DrawingArea ();
			this.locationSeparator.HeightRequest = 1;
			this.locationSeparator.Name = "locationSeparator";
			this.projectConfigurationTable.Add (this.locationSeparator);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.locationSeparator]));
			w6.TopAttach = ((uint)(3));
			w6.BottomAttach = ((uint)(4));
			w6.RightAttach = ((uint)(3));
			w6.YPadding = ((uint)(10));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.locationTextBox = new global::Gtk.Entry ();
			this.locationTextBox.CanFocus = true;
			this.locationTextBox.Name = "locationTextBox";
			this.locationTextBox.IsEditable = true;
			this.locationTextBox.InvisibleChar = '●';
			this.projectConfigurationTable.Add (this.locationTextBox);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.locationTextBox]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.moduleNameLabel = new global::Gtk.Label ();
			this.moduleNameLabel.Name = "moduleNameLabel";
			this.moduleNameLabel.Xpad = 5;
			this.moduleNameLabel.Xalign = 1F;
			this.moduleNameLabel.LabelProp = "Module Name:";
			this.moduleNameLabel.Justify = ((global::Gtk.Justification)(1));
			this.projectConfigurationTable.Add (this.moduleNameLabel);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.moduleNameLabel]));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.moduleNameTextBox = new global::Gtk.Entry ();
			this.moduleNameTextBox.CanFocus = true;
			this.moduleNameTextBox.Name = "moduleNameTextBox";
			this.moduleNameTextBox.IsEditable = true;
			this.moduleNameTextBox.InvisibleChar = '●';
			this.projectConfigurationTable.Add (this.moduleNameTextBox);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.moduleNameTextBox]));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.solutionNameSeparator = new global::Gtk.DrawingArea ();
			this.solutionNameSeparator.HeightRequest = 1;
			this.solutionNameSeparator.Name = "solutionNameSeparator";
			this.projectConfigurationTable.Add (this.solutionNameSeparator);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.solutionNameSeparator]));
			w10.TopAttach = ((uint)(1));
			w10.BottomAttach = ((uint)(2));
			w10.RightAttach = ((uint)(3));
			w10.YPadding = ((uint)(10));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.useGitCheckBox = new global::Gtk.CheckButton ();
			this.useGitCheckBox.CanFocus = true;
			this.useGitCheckBox.Name = "useGitCheckBox";
			this.useGitCheckBox.Label = "Use git for version control.";
			this.useGitCheckBox.Active = true;
			this.useGitCheckBox.DrawIndicator = true;
			this.useGitCheckBox.UseUnderline = true;
			this.projectConfigurationTable.Add (this.useGitCheckBox);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.useGitCheckBox]));
			w11.TopAttach = ((uint)(4));
			w11.BottomAttach = ((uint)(5));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child projectConfigurationTable.Gtk.Table+TableChild
			this.versionControlLabelHBox = new global::Gtk.HBox ();
			this.versionControlLabelHBox.Name = "versionControlLabelHBox";
			// Container child versionControlLabelHBox.Gtk.Box+BoxChild
			this.versionControlSpacerLabel = new global::Gtk.Label ();
			this.versionControlSpacerLabel.WidthRequest = 7;
			this.versionControlSpacerLabel.Name = "versionControlSpacerLabel";
			this.versionControlSpacerLabel.Justify = ((global::Gtk.Justification)(1));
			this.versionControlLabelHBox.Add (this.versionControlSpacerLabel);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.versionControlLabelHBox [this.versionControlSpacerLabel]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child versionControlLabelHBox.Gtk.Box+BoxChild
			this.versionControlLabel = new global::Gtk.Label ();
			this.versionControlLabel.Name = "versionControlLabel";
			this.versionControlLabel.Xpad = 5;
			this.versionControlLabel.Xalign = 1F;
			this.versionControlLabel.LabelProp = "Version Control:";
			this.versionControlLabel.Justify = ((global::Gtk.Justification)(1));
			this.versionControlLabelHBox.Add (this.versionControlLabel);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.versionControlLabelHBox [this.versionControlLabel]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.projectConfigurationTable.Add (this.versionControlLabelHBox);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.projectConfigurationTable [this.versionControlLabelHBox]));
			w14.TopAttach = ((uint)(4));
			w14.BottomAttach = ((uint)(5));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			this.projectConfigurationVBox.Add (this.projectConfigurationTable);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.projectConfigurationVBox [this.projectConfigurationTable]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child projectConfigurationVBox.Gtk.Box+BoxChild
			this.projectConfigurationBottomEventBox = new global::Gtk.EventBox ();
			this.projectConfigurationBottomEventBox.Name = "projectConfigurationBottomEventBox";
			this.projectConfigurationVBox.Add (this.projectConfigurationBottomEventBox);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.projectConfigurationVBox [this.projectConfigurationBottomEventBox]));
			w16.Position = 2;
			this.projectConfigurationTableEventBox.Add (this.projectConfigurationVBox);
			this.mainHBox.Add (this.projectConfigurationTableEventBox);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.mainHBox [this.projectConfigurationTableEventBox]));
			w18.Position = 1;
			// Container child mainHBox.Gtk.Box+BoxChild
			this.projectConfigurationRightBorderEventBox = new global::Gtk.EventBox ();
			this.projectConfigurationRightBorderEventBox.WidthRequest = 30;
			this.projectConfigurationRightBorderEventBox.Name = "projectConfigurationRightBorderEventBox";
			this.mainHBox.Add (this.projectConfigurationRightBorderEventBox);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.mainHBox [this.projectConfigurationRightBorderEventBox]));
			w19.Position = 2;
			w19.Expand = false;
			// Container child mainHBox.Gtk.Box+BoxChild
			this.eventBox = new global::Gtk.EventBox ();
			this.eventBox.Name = "eventBox";
			// Container child eventBox.Gtk.Container+ContainerChild
			this.previewProjectFolderVBox = new global::Gtk.VBox ();
			this.previewProjectFolderVBox.Name = "previewProjectFolderVBox";
			this.previewProjectFolderVBox.Spacing = 6;
			this.previewProjectFolderVBox.BorderWidth = ((uint)(20));
			// Container child previewProjectFolderVBox.Gtk.Box+BoxChild
			this.projectFolderPreviewWidget = new global::MonoDevelop.Ide.Projects.GtkProjectFolderPreviewWidget ();
			this.projectFolderPreviewWidget.WidthRequest = 240;
			this.projectFolderPreviewWidget.Events = ((global::Gdk.EventMask)(256));
			this.projectFolderPreviewWidget.Name = "projectFolderPreviewWidget";
			this.previewProjectFolderVBox.Add (this.projectFolderPreviewWidget);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.previewProjectFolderVBox [this.projectFolderPreviewWidget]));
			w20.Position = 0;
			this.eventBox.Add (this.previewProjectFolderVBox);
			this.mainHBox.Add (this.eventBox);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.mainHBox [this.eventBox]));
			w22.Position = 3;
			this.Add (this.mainHBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
